"""add sample_rate tag_version comment to tracks

Revision ID: 30c6cc7f8f59
Revises: d9d95ec34c48
Create Date: 2026-03-18 16:34:54.954266

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '30c6cc7f8f59'
down_revision: Union[str, None] = 'd9d95ec34c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('sample_rate', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('tag_version', sa.String(length=20), nullable=True))
    op.add_column('tracks', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'comment')
    op.drop_column('tracks', 'tag_version')
    op.drop_column('tracks', 'sample_rate')
    # ### end Alembic commands ###
