"""add_album_description

Revision ID: 7df181314453
Revises: 0006
Create Date: 2026-03-19 11:48:28.663824

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7df181314453'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_log_created_at', table_name='activity_log')
    op.drop_index('ix_activity_log_log_type', table_name='activity_log')
    op.add_column('albums', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'description')
    op.create_index('ix_activity_log_log_type', 'activity_log', ['log_type'], unique=False)
    op.create_index('ix_activity_log_created_at', 'activity_log', ['created_at'], unique=False)
    # ### end Alembic commands ###
