"""add_track_metadata_fields

Revision ID: d9d95ec34c48
Revises: 0005
Create Date: 2026-03-09 22:17:06.497955

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd9d95ec34c48'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_scan_folders_id'), 'scan_folders', ['id'], unique=False)
    op.drop_index('ix_scan_log_started_at', table_name='scan_log')
    op.add_column('tracks', sa.Column('total_tracks', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('release_date', sa.String(length=20), nullable=True))
    op.add_column('tracks', sa.Column('label', sa.String(length=200), nullable=True))
    op.add_column('tracks', sa.Column('isrc', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_column('tracks', 'isrc')
    op.drop_column('tracks', 'label')
    op.drop_column('tracks', 'release_date')
    op.drop_column('tracks', 'total_tracks')
    op.create_index('ix_scan_log_started_at', 'scan_log', ['started_at'], unique=False)
    op.drop_index(op.f('ix_scan_folders_id'), table_name='scan_folders')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    # ### end Alembic commands ###
